<a href="https://colab.research.google.com/github/shubhe25p/ResNet-from-scratch-Pytorch/blob/test/samplenet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
torch.cuda.is_available()

True

In [5]:
!nvidia-smi

Sat Apr 24 10:36:48 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [6]:
my_tensor=torch.tensor(np.random.rand(3,4))

In [7]:
my_tensor.to("cuda")

tensor([[0.3391, 0.3842, 0.5118, 0.2598],
        [0.4201, 0.8922, 0.1455, 0.9060],
        [0.2281, 0.6602, 0.0165, 0.5521]], device='cuda:0',
       dtype=torch.float64)

In [8]:
my_tensor*my_tensor

tensor([[1.1501e-01, 1.4762e-01, 2.6194e-01, 6.7490e-02],
        [1.7645e-01, 7.9606e-01, 2.1181e-02, 8.2082e-01],
        [5.2052e-02, 4.3585e-01, 2.7171e-04, 3.0478e-01]], dtype=torch.float64)

In [ ]:
my_tensor.matmul(my_tensor.T)

tensor([[1.2324, 1.3741, 1.1149],
        [1.3741, 2.1569, 1.4128],
        [1.1149, 1.4128, 1.4151]], dtype=torch.float64)

In [ ]:
my_tensor @ my_tensor.T

tensor([[1.2324, 1.3741, 1.1149],
        [1.3741, 2.1569, 1.4128],
        [1.1149, 1.4128, 1.4151]], dtype=torch.float64)

In [ ]:
torch.nn.functional.softmax(my_tensor, dim=0)

tensor([[0.3094, 0.4258, 0.2526, 0.2823],
        [0.3535, 0.2752, 0.3471, 0.5023],
        [0.3370, 0.2990, 0.4003, 0.2154]], dtype=torch.float64)

In [ ]:
torch.rand(1,2,2,3)

tensor([[[[0.7306, 0.7314, 0.3509],
          [0.6193, 0.3747, 0.9781]],

         [[0.7917, 0.9425, 0.4403],
          [0.5069, 0.2976, 0.1779]]]])

In [ ]:
my_tensor.clip(0.2,0.8)

tensor([[0.5633, 0.2000, 0.8000, 0.2650],
        [0.5392, 0.7844, 0.3762, 0.7459],
        [0.2000, 0.6215, 0.8000, 0.7315]], dtype=torch.float64)

In [ ]:
torch.ones(1,2)

tensor([[1., 1.]])

In [ ]:
torch.device

torch.device

In [ ]:
torch.get_num_threads()

1

In [ ]:
a = torch.tensor([5.], requires_grad=True)
b = torch.tensor([6.], requires_grad=True)

In [ ]:
a

tensor([5.], requires_grad=True)

In [ ]:
y = a**3 -b**2

In [ ]:
y.backward()

In [ ]:
print(a.grad)

tensor([75.])


In [ ]:
W = torch.rand(10,1, requires_grad=True)
W

tensor([[0.8391],
        [0.8638],
        [0.3635],
        [0.4724],
        [0.3941],
        [0.5406],
        [0.8557],
        [0.6668],
        [0.5588],
        [0.3464]], requires_grad=True)

In [ ]:
x=torch.rand(1,10)
b=torch.rand(1,1)

In [ ]:
op = torch.matmul(x,W) + b
op.shape

torch.Size([1, 1])

In [ ]:
loss = 1 - op
op

tensor([[3.7148]], grad_fn=<AddBackward0>)

In [ ]:
loss.backward()

In [ ]:
W.grad.data

tensor([[-0.9469],
        [-0.2981],
        [-0.8220],
        [-0.7769],
        [-0.6005],
        [-0.4380],
        [-0.2791],
        [-0.8605],
        [-0.4555],
        [-0.2733]])

In [ ]:
import torch, torchvision
model = torchvision.models.resnet18(pretrained=True)
data = torch.rand(1,3,64,64)
labels = torch.rand(1, 1000)

Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /root/.cache/torch/hub/checkpoints/resnet18-5c106cde.pth


In [ ]:
prediction = model(data)

In [ ]:
loss = (prediction - labels).sum()
loss.backward()

In [ ]:
optim = torch.optim.SGD(model.parameters(), lr=0.005, momentum=0.9)

In [ ]:
optim.step()

In [12]:
test1=torch.rand(1,3,8,8)

In [9]:
import torch
from torch.autograd import Variable
from torch.nn import Linear, ReLU, CrossEntropyLoss, Sequential, Conv2d, MaxPool2d, Module, Softmax, BatchNorm2d, Dropout
from torch.optim import Adam, SGD

In [13]:
conv_layer = Conv2d( 3, 8, 5, )
output = conv_layer(test1)
output.shape

torch.Size([1, 8, 4, 4])

In [111]:
from torch.nn import Conv2d, functional as F, Linear, MaxPool2d, Module, Sequential
class SimpleNet(Module):

  def __init__(self):
    super(SimpleNet, self).__init__()
    
    self.cnn_layers = Sequential(
        Conv2d(1, 4,  kernel_size=3,  stride=1, padding=1),
        BatchNorm2d(4),
        ReLU(inplace=True),
        MaxPool2d(kernel_size=2, stride=2),

        Conv2d(4, 4, kernel_size=3, stride=1, padding=1),
        BatchNorm2d(4),
        ReLU(inplace=True),
        MaxPool2d(kernel_size=2, stride=2),
    )

    self.linear_layers = Sequential(
        Linear(4 * 7 * 7, 10)
    )


  def forward(self, x):
    

    x = self.cnn_layers(x)
    x = x.view(x.size(0),-1)
    x = self.linear_layers(x)
    return x

In [112]:
model = SimpleNet()
optimizer = Adam(model.parameters(), lr=0.07)
criterion = CrossEntropyLoss()

if torch.cuda.is_available():

  model = model.cuda()
  criterion = criterion.cuda()

print(model)

SimpleNet(
  (cnn_layers): Sequential(
    (0): Conv2d(1, 4, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): BatchNorm2d(4, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
    (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (4): Conv2d(4, 4, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (5): BatchNorm2d(4, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (6): ReLU(inplace=True)
    (7): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (linear_layers): Sequential(
    (0): Linear(in_features=196, out_features=10, bias=True)
  )
)


In [103]:
print(model)

SimpleNet(
  (cnn_layers): Sequential(
    (0): Conv2d(1, 4, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): BatchNorm2d(4, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
    (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (4): Conv2d(4, 4, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (5): BatchNorm2d(4, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (6): ReLU(inplace=True)
    (7): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (linear_layers): Sequential(
    (0): Linear(in_features=196, out_features=10, bias=True)
  )
)


In [183]:
data_test = MNIST('~/mnist_data', train=, download=True)
data_test.shape

AttributeError: ignored

In [149]:
import torch
from torchvision.datasets import MNIST 

data_train  = MNIST('~/mnist_data', train=True, download=True)




Extracting /root/mnist_data/MNIST/raw/train-images-idx3-ubyte.gz to /root/mnist_data/MNIST/raw




Extracting /root/mnist_data/MNIST/raw/train-labels-idx1-ubyte.gz to /root/mnist_data/MNIST/raw

Failed to download (trying next):
HTTP Error 503: Service Unavailable




Extracting /root/mnist_data/MNIST/raw/t10k-images-idx3-ubyte.gz to /root/mnist_data/MNIST/raw

Failed to download (trying next):
HTTP Error 503: Service Unavailable




Extracting /root/mnist_data/MNIST/raw/t10k-labels-idx1-ubyte.gz to /root/mnist_data/MNIST/raw

Processing...
Done!


/usr/local/lib/python3.7/dist-packages/torchvision/datasets/mnist.py:502: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:143.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)


In [179]:
data_train  = torch.utils.data.DataLoader(
    MNIST(
        '~/mnist_data', train=True, download=True,
        transform = transforms.Compose([
              transforms.ToTensor()
        ])),
        batch_size=64,
        shuffle=True
    )
for _, data in enumerate(data_train):
  print(data[1].shape)
  break

torch.Size([64])


In [139]:
torch.cuda.empty_cache()
torch.cuda.memory_summary(device='cuda')

'|===========================================================================|\n|                  PyTorch CUDA memory summary, device ID 0                 |\n|---------------------------------------------------------------------------|\n|            CUDA OOMs: 15           |        cudaMalloc retries: 15        |\n|===========================================================================|\n|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |\n|---------------------------------------------------------------------------|\n| Allocated memory      |   13034 MB |   13685 MB |  569894 MB |  556859 MB |\n|       from large pool |   13020 MB |   13670 MB |  569601 MB |  556581 MB |\n|       from small pool |      14 MB |      16 MB |     292 MB |     278 MB |\n|---------------------------------------------------------------------------|\n| Active memory         |   13034 MB |   13685 MB |  569894 MB |  556859 MB |\n|       from large pool |   13020 MB |   13670 MB |

In [184]:
x_test_np = x__test.reshape(10000, 1, 28, 28)
x_test_tensor = torch.as_tensor(x_test_np, dtype=torch.float32)
x_test_tensor.shape

torch.Size([10000, 1, 28, 28])

In [177]:
train_loader  = torch.utils.data.DataLoader(x_train_tensor, batch_size=8)
for data in train_loader:
  print(data.shape)
  break

torch.Size([8, 1, 28, 28])


In [141]:
y_train_np  = y__train.astype(int)
y_train_tensor  = torch.from_numpy(y_train_np)
y_test_np = y__test.astype(int)
y_test_tensor = torch.from_numpy(y_test_np)
y_test_tensor.dtype

torch.int64

In [180]:
n_epoch = 25
train_losses  = []
test_losses =  []

def train(epoch):

  model.train()
  tr_loss = 0

  for batch_idx, data in enumerate(data_train):
    x_train = data[0]
    y_train = data[1]
    if torch.cuda.is_available():
      
      x_train = x_train.cuda()
      y_train = y_train.cuda()
      #x_test  = x_test.cuda()
      #y_test  = y_test.cuda()

      optimizer.zero_grad()

      output_train  = model(x_train)
    #output_test  = model(x_test)

      loss_train  = criterion(output_train, y_train)
    #loss_test = criterion(output_test,  y_test)
      train_losses.append(loss_train)
    #test_losses.append(loss_test)

      loss_train.backward()
      optimizer.step()
      tr_loss = loss_train.item()

  if epoch%2 ==0:
    print('Epoch  :', epoch+1, '\t', 'loss:', loss_train)
    

In [181]:
torch.cuda.empty_cache()
for epoch in range(n_epoch):
  train(epoch)

Epoch  : 1 	 loss: tensor(0.1303, device='cuda:0', grad_fn=<NllLossBackward>)
Epoch  : 3 	 loss: tensor(0.1167, device='cuda:0', grad_fn=<NllLossBackward>)
Epoch  : 5 	 loss: tensor(0.2352, device='cuda:0', grad_fn=<NllLossBackward>)
Epoch  : 7 	 loss: tensor(0.1362, device='cuda:0', grad_fn=<NllLossBackward>)
Epoch  : 9 	 loss: tensor(0.0875, device='cuda:0', grad_fn=<NllLossBackward>)
Epoch  : 11 	 loss: tensor(0.0853, device='cuda:0', grad_fn=<NllLossBackward>)
Epoch  : 13 	 loss: tensor(0.1778, device='cuda:0', grad_fn=<NllLossBackward>)
Epoch  : 15 	 loss: tensor(0.1741, device='cuda:0', grad_fn=<NllLossBackward>)
Epoch  : 17 	 loss: tensor(0.0308, device='cuda:0', grad_fn=<NllLossBackward>)
Epoch  : 19 	 loss: tensor(0.0123, device='cuda:0', grad_fn=<NllLossBackward>)
Epoch  : 21 	 loss: tensor(0.0314, device='cuda:0', grad_fn=<NllLossBackward>)
Epoch  : 23 	 loss: tensor(0.0086, device='cuda:0', grad_fn=<NllLossBackward>)
Epoch  : 25 	 loss: tensor(0.0512, device='cuda:0', grad_

In [185]:
def test():
  
  x_test, y_test  = torch.tensor(x_test_tensor, requires_grad=True),  torch.tensor(y_test_tensor, dtype=torch.long)

  if torch.cuda.is_available():

    x_test  = x_test.cuda()
    y_test  = y_test.cuda()
    output_test  = model(x_test)
    loss_test = criterion(output_test,  y_test)
  
  print(loss_test)



In [186]:
test()

tensor(0.1213, device='cuda:0', grad_fn=<NllLossBackward>)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  This is separate from the ipykernel package so we can avoid doing imports until
